// Generated by CoffeeScript 1.4.0
(function() {
  var Auth, Models, app, auth, cfg, express, isJson, isLoggedIn, models;

  express = require('express');

  Auth = (require('./lib/auth.js')).Auth;

  Models = (require('./lib/models.js')).Models;

  cfg = require('./cfg/config.js');

  app = express();

  app.use(express.bodyParser());

  app.use(express.cookieParser());

  app.use(express.session({
    secret: 'blahblahblah'
  }));

  app.set('views', __dirname + '/views');

  app.engine('jade', require('jade').__express);

  /* Controllers
  */


  auth = new Auth;

  models = new Models;

  /* Routes
  */


  app.get('/', function(req, res) {
    if (!isLoggedIn(req.session)) {
      return res.redirect('/login');
    } else {
      return res.redirect('/models');
    }
  });

  app.get('/login', function(req, res) {
    return auth.login(function(error, callback) {
      req.session.oauth_token = callback.oauth_token;
      req.session.oauth_token_secret = callback.oauth_token_secret;
      return res.redirect(callback.url);
    });
  });

  app.get('/callback', function(req, res) {
    return auth.handleCallback(req.query.oauth_token, req.session.oauth_token_secret, req.query.oauth_verifier, function(callback) {
      req.session.oauth_access_token = callback.oauth_access_token;
      req.session.oauth_access_token_secret = callback.oauth_access_token_secret;
      return res.redirect('/');
    });
  });

  app.get('/upload', function(req, res) {
    if (!isLoggedIn(req.session)) {
      return res.redirect('/login');
    } else {
      return res.render('models/upload.jade');
    }
  });

  app.post('/models/upload', function(req, res) {
    if (!isLoggedIn(req.session)) {
      return res.redirect('/login');
    } else {
      return models.putModel(req.files.modelUpload, req.session.oauth_access_token, req.session.oauth_access_token_secret, function(callback) {
        return res.render('models/upload_success.jade', {
          "callback": JSON.parse(callback),
          "server": cfg.API_SERVER
        });
      });
    }
  });

  app.get('/models/:id', function(req, res) {
    if (!isLoggedIn(req.session)) {
      return res.redirect('/login');
    } else {
      return models.getModel(req.params.id, req.session.oauth_access_token, req.session.oauth_access_token_secret, function(callback) {
        if (isJson(req.url)) {
          return res.send(JSON.parse(callback));
        } else {
          return res.render('models/id.jade', {
            "callback": JSON.parse(callback),
            "server": cfg.API_SERVER
          });
        }
      });
    }
  });

  app.get('/models*', function(req, res) {
    if (!isLoggedIn(req.session)) {
      return res.redirect('/login');
    } else {
      return models.getModels(req.session.oauth_access_token, req.session.oauth_access_token_secret, function(callback) {
        if (isJson(req.url)) {
          return res.send(JSON.parse(callback));
        } else {
          return res.render('models/index.jade', {
            "callback": JSON.parse(callback)
          });
        }
      });
    }
  });

  app.get('/logout', function(req, res) {
    req.session.destroy();
    return res.redirect('/');
  });

  /* Start the App
  */


  app.listen('3000');

  isLoggedIn = function(session) {
    if (!session.oauth_access_token) {
      return false;
    }
    return true;
  };

  isJson = function(url) {
    var json;
    json = false;
    if ((url.substring(url.length - 5)) === ".json") {
      json = true;
    }
    return json;
  };

}).call(this);
