// Generated by CoffeeScript 1.4.0

/* Tests for Auth /lib/auth.coffee
*/


(function() {
  var auth, authClass, cfg, should;

  cfg = require('../cfg/config.js');

  should = require('should');

  authClass = (require('../lib/auth.js')).Auth;

  auth = new authClass(cfg);

  describe("Testing login", function() {
    var serverName;
    serverName = process.env.API_SERVER;
    return it("Should login successfully", function(done) {
      return auth.login(function(error, callback) {
        var index;
        should.not.exist(error);
        callback.should.have.property('url');
        index = callback.url.indexOf(serverName);
        index.should.be.above(-1);
        return done();
      });
    });
  });

}).call(this);
