// Generated by CoffeeScript 1.4.0

/* Tests for Models /model
*/


(function() {

  describe('upload a model', function() {
    it('should accept a valid .stl file');
    it('should display an error when an invalid model is specified');
    return it('should receive a successful response from the server when a valid model is uplaoded ');
  });

  describe('edit a model', function() {});

  describe('view a list of models', function() {
    it('should return a list of models when no parameter is specified');
    it('should list private models');
    return it('should list public models');
  });

  describe('view model by id', function() {
    it('should return a single model');
    return it('should return null when an invalid model is specified');
  });

  /* Usage 
  describe('test', function(){
    it('should work with objects', function(){
      var a = { name: 'tobi', age: 2, species: 'ferret' };
      var b = { name: 'jane', age: 8, species: 'ferret' };
      a.should.eql(b);
    })
  
    it('should work with arrays', function(){
      var a = [1,2,{ name: 'tobi' },4,5]
      var b = [1,2,{ name: 'jane' },4,4, 'extra stuff', 'more extra']
      a.should.eql(b);
    })
  
    it('should work with strings', function(){
      'some\nfoo\nbar'.should.equal('some\nbar\nbaz');
    })
  })
  */


}).call(this);
